AllCops:
  TargetRubyVersion: 2.3

Layout/DotPosition:
  EnforcedStyle: trailing
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/MethodLength:
  Exclude:
    - 'gen/**/*'
Metrics/ParameterLists:
  Exclude:
    - 'gen/**/*'
Metrics/LineLength:
  Exclude:
    - 'gen/**/*'
Style/DoubleNegation:
  Exclude:
    - 'gen/**/*'
Layout/TrailingWhitespace: # TODO: remove
  Exclude:
    - 'gen/**/*'
Metrics/AbcSize:
  Exclude:
    - 'gen/**/*'
Metrics/CyclomaticComplexity:
  Exclude:
    - 'gen/**/*'
Metrics/PerceivedComplexity:
  Exclude:
    - 'gen/**/*'
Metrics/BlockLength:
  Exclude:
    - 'gen/**/*'
Metrics/ModuleLength:
  Exclude:
    - 'gen/**/*'
Style/Documentation:
  Exclude:
    - 'gen/**/*'
    - 'lib/**/*' # TODO: remove
Naming/AccessorMethodName:
  Exclude:
    - 'gen/**/*'
